services:
  db:
    image: cgr.dev/chainguard/postgres
    restart: always
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: foody_development
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: cgr.dev/chainguard/postgres
    restart: always
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: foody_test
    ports:
      - 5433:5432
    volumes:
      - pgtestdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pgtestdata:
