# fly.toml app configuration file generated for foody-v2 on 2024-10-20T21:33:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foody-v2'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  entrypoint = ['/usr/app/foody-cli', 'start', '--binding', '0.0.0.0']

[env]
  LOCO_ENV = 'production'

[http_service]
  internal_port = 5150
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
