//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod ingredients;
pub mod ingredients_in_recipes;
pub mod ingredients_in_shoppinglists;
pub mod quantities;
pub mod recipes;
pub mod shoppinglists;
pub mod tags;
pub mod tags_on_ingredients;
pub mod users;
