//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod aisles;
pub mod ingredients;
pub mod ingredients_in_recipes;
pub mod ingredients_in_shoppinglists;
pub mod meal_plans;
pub mod meals_in_meal_plans;
pub mod quantities;
pub mod recipes;
pub mod shoppinglists;
pub mod storages;
pub mod users;
