//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::{
    ingredients::Entity as Ingredients,
    ingredients_in_shoppinglists::Entity as IngredientsInShoppinglists, notes::Entity as Notes,
    quantities::Entity as Quantities, shoppinglists::Entity as Shoppinglists,
    users::Entity as Users,
};
