//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::ingredients::Entity as Ingredients;
pub use super::ingredients_in_recipes::Entity as IngredientsInRecipes;
pub use super::ingredients_in_shoppinglists::Entity as IngredientsInShoppinglists;
pub use super::quantities::Entity as Quantities;
pub use super::recipes::Entity as Recipes;
pub use super::shoppinglists::Entity as Shoppinglists;
pub use super::users::Entity as Users;
