//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::aisles::Entity as Aisles;
pub use super::ingredients::Entity as Ingredients;
pub use super::ingredients_in_recipes::Entity as IngredientsInRecipes;
pub use super::ingredients_in_shoppinglists::Entity as IngredientsInShoppinglists;
pub use super::meal_plans::Entity as MealPlans;
pub use super::meals_in_meal_plans::Entity as MealsInMealPlans;
pub use super::quantities::Entity as Quantities;
pub use super::recipes::Entity as Recipes;
pub use super::shoppinglists::Entity as Shoppinglists;
pub use super::users::Entity as Users;
