name: Fly Deploy
on:
  workflow_run:
    workflows: [CI]
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      concurrency: deploy-group
      needs:
        - fmt
        - lint
        - test
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
          with:
            version: 0.1.84
        - run: flyctl deploy --remote-only --build-arg=GIT_SHA=$GITHUB_SHA
